package org.dimalei.wiimvolumesync.data

import android.annotation.SuppressLint
import java.security.cert.CertificateException
import java.security.cert.X509Certificate
import javax.net.ssl.X509TrustManager

/*
* Trickery to get the self signed SSL Certificate
* generated by some AI
 */
@SuppressLint("CustomX509TrustManager")
class CertCapturingTrustManager : X509TrustManager {
    @Volatile
    var capturedChain: Array<X509Certificate>? = null
        private set

    override fun checkServerTrusted(chain: Array<X509Certificate>, authType: String) {
        // Capture what the server presented
        capturedChain = chain.clone()
        // Abort the handshake: we are not trusting anything here
        throw CertificateException("Capture-only TrustManager: not trusting this server")
    }

    override fun checkClientTrusted(chain: Array<X509Certificate>, authType: String) {
        throw CertificateException("Client certs not supported")
    }

    override fun getAcceptedIssuers(): Array<X509Certificate> = emptyArray()
}